server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: C:/Users/Drissi houcem eddine/Desktop/Learning/Spring-Slides/config-service/src/main/resources/myConfig
  application:
    name: config-service