server:
  port: 9999

spring:
  main:
    allow-circular-references: true

 zuul:
   ignored-services: '*'
   routes:
     product-service:
      path: /product-service/**
      stripPrefix: true
      sensitiveHeaders: 
